version: '3.0'

services:
  service:
    container_name: shipment
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 8082:8082
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/shipment
    depends_on:
      - shipment-db
  shipment-db:
    image: postgres
    container_name: shipment-db
    restart: always
    command: ['-p', '5433']
    ports:
      - 5433:5433
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: account
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres