apiVersion: v1
kind: Service
metadata:
  name: credit-service # Sets service name
  labels:
    app: credit-service # Labels and Selectors
    version: v1
spec:
  type: ClusterIP # Sets service type
  ports:
    - name: http
      protocol: TCP
      port: 8086
      targetPort: 8086
  selector:
    app: credit-service