apiVersion: v1
kind: Service
metadata:
  name: order-service # Sets service name
  labels:
    app: order-service # Labels and Selectors
    version: v1
spec:
  type: NodePort # Sets service type
  ports:
    - name: http
      protocol: TCP
      port: 8083
      targetPort: 8083
      nodePort: 30083
  selector:
    app: order-service