apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
        version: v1
    spec:
      containers:
        - name: product-service
          image: product-service:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8084
          envFrom:
            - configMapRef:
                name: product-config
          securityContext:
            runAsUser: 1000