apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-database  # Sets Deployment name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-database
  template:
    metadata:
      labels:
        app: account-database
        version: v1
    spec:
      containers:
        - name: account-database
          image: postgres # Sets Image
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432  # Exposes container port
          envFrom:
            - configMapRef:
                name: account-db-config
#          volumeMounts:
#            - mountPath: /var/lib/postgresql/data
#              name: postgres-db
#      volumes:
#        - name: postgres-db
#          persistentVolumeClaim:
#            claimName: db1-pv-claim