apiVersion: v1
kind: Service
metadata:
  name: account-database # Sets service name
  labels:
    app: account-database # Labels and Selectors
spec:
  type: ClusterIP # Sets service type
  ports:
    - protocol: TCP
      port: 5432 # Sets port to run the postgres application
      targetPort: 5432
  selector:
    app: account-database