apiVersion: v1
kind: Service
metadata:
  name: payment-service # Sets service name
  labels:
    app: payment-service # Labels and Selectors
    version: v1
spec:
  type: NodePort # Sets service type
  ports:
    - name: http
      protocol: TCP
      port: 8085
      targetPort: 8085
      nodePort: 30084
  selector:
    app: payment-service