spring:
  application:
    name: bank-service
  cloud:
    loadbalancer:
      ribbon:
        enable: false

server:
  port: 8087
  error:
    include-message: always

shipment-service:
  ribbon:
    listOfServers: ${SHIPMENT_SERVICE:http://localhost:8082}
order-service:
  ribbon:
    listOfServers: ${ORDER_SERVICE:http://localhost:8083}