apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: http-app-1
  namespace: default

spec:
  parentRefs:
    - name: traefik-gateway

  rules:
    - matches:
        - path:
            type: Exact
            value: /account

      backendRefs:
        - name: account-service
          port: 8081
          weight: 1