apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bank-service
  template:
    metadata:
      labels:
        app: bank-service
        version: v1
    spec:
      containers:
        - name: bank-service
          image: bank-service:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8087
          envFrom:
            - configMapRef:
                name: bank-config
          securityContext:
            runAsUser: 1000