
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/account
    username: postgres
    password: postgres

  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true

  jpa:
    hibernate:
      ddl-auto: create

    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
  application:
    name: product-service
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

server:
  port: 8084
  error:
    include-message: always

custom:
  shortage-amount: ${SHORTAGE_AMOUNT:50}