apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipment-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shipment-service
  template:
    metadata:
      labels:
        app: shipment-service
        version: v1
    spec:
      containers:
        - name: shipment-service
          image: shipment-service:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8083
          envFrom:
            - configMapRef:
                name: shipment-config
          securityContext:
            runAsUser: 1000