apiVersion: v1
kind: Service
metadata:
  name: account-service # Sets service name
  labels:
    app: account-service # Labels and Selectors
    version: v1
spec:
  type: NodePort # Sets service type
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30081
  selector:
    app: account-service