apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
        version: v1
    spec:
      containers:
        - name: account-service
          image: account-service:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: account-config
          securityContext:
            runAsUser: 1000